FROM ubuntu:14.04
RUN apt-get -y update
RUN apt-get -y install ruby1.9.3=1.9.3*

RUN apt-get install -y build-essential

RUN apt-get install -y libxml2-dev

RUN apt-get install -y libpcre3
RUN apt-get install -y libpcre3-dev

RUN apt-get install -y tcl

RUN apt-get install -y libicu-dev

RUN apt-get install -y libxslt1-dev

RUN apt-get install -y libmysqlclient-dev

RUN apt-get install -y ruby-dev

RUN apt-get install -y python-mysqldb

RUN apt-get install -y software-properties-common

RUN apt-get install -y mysql-client

RUN apt-get install -y tnef
